### ISSUE TITLE
Sobre a operação

### ISSUE THREAD

**Issue by ricardojbs** [eduardoarn/NegocieCoinsTrade#1]
Olá Eduardo, tenho uma dúvida: o projeto está operando normalmente?

Desde já parabéns pelo projeto :D

**Comment by eduardoarn** [comment]
Olá @ricardojbs, muito obrigado.

O projeto está parado porque a negociecoins desativou a API de negociação desde Janeiro, a ideia era fazer negociação pelo app sem precisar entrar no site deles trazendo mobilidade. Mas a complexidade fornecida na API de neociação deles me obrigou a criar um servidor em ASP.NET pra operar como intermediário pra criptografar a comunicação chegou até a funcionar no início do desenvolvimento estava até buscando o saldo da conta.

Se quiser dá uma conferida ele tá disponível nesse endereço: https://negociecoins.tk

Por essa desativação da API eu decidi por dá uma pausa até normalizar, porque particularmente eu gosto muito das taxas deles.
